# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  test:
    docker:
      - image: circleci/golang:1.12.5-stretch
    working_directory: /go/src/github.com/s-rafaeldias/avatarme
    steps:
      - checkout
      - run: make go_get
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run: make test_ci
      - codecov/upload:
          file: /tmp/artifacts/c.txt

workflows:
  version: 2
  test:
    jobs:
      - test


